namespace App6
{
    [default_interface]
    runtimeclass SettingsCard : Microsoft.UI.Xaml.Controls.UserControl
    {
        SettingsCard();

        static Microsoft.UI.Xaml.DependencyProperty HeaderProperty{ get; };
        String Header;

        static Microsoft.UI.Xaml.DependencyProperty DescriptionProperty{ get; };
        String Description;

        static Microsoft.UI.Xaml.DependencyProperty IsOnProperty{ get; };
        Boolean IsOn;
    }
}
